import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowRight, Shield, Zap, Brain } from "lucide-react";
import AnimatedBackground from "@/components/AnimatedBackground";
import AgentCard from "@/components/AgentCard";
import { agents } from "@/lib/mock-data";
import { useState } from "react";

const pageVariants = {
  initial: { opacity: 0 },
  animate: { opacity: 1, transition: { duration: 0.5, staggerChildren: 0.1 } },
  exit: { opacity: 0 },
};

const LandingPage = () => {
  const [openAgent, setOpenAgent] = useState<string | null>(null);

  return (
    <motion.div variants={pageVariants} initial="initial" animate="animate" exit="exit" className="relative min-h-screen">
      <AnimatedBackground />

      {/* Hero */}
      <section className="relative flex min-h-screen flex-col items-center justify-center px-4 pt-16 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="max-w-3xl"
        >
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5 text-xs font-medium text-primary">
            <Zap size={12} />
            Multi-Agent AI Detection
          </div>
          <h1 className="mb-6 text-4xl font-black tracking-tight sm:text-6xl lg:text-7xl">
            Detect AI Text with{" "}
            <span className="text-gradient">CheckWise</span>
          </h1>
          <p className="mx-auto mb-8 max-w-xl text-base text-muted-foreground sm:text-lg">
            Four specialized AI agents work together to determine if text was written by a human or generated by AI. Fast, accurate, and transparent.
          </p>
          <div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
            <Link
              to="/checker"
              className="group inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 text-sm font-bold text-primary-foreground transition-all cyber-glow hover:cyber-glow-strong"
            >
              Start Checking
              <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" />
            </Link>
            <Link
              to="/register"
              className="inline-flex items-center gap-2 rounded-lg border border-border px-6 py-3 text-sm font-medium text-foreground transition-colors hover:bg-secondary"
            >
              Create Account
            </Link>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8, duration: 1 }}
          className="absolute bottom-8 flex flex-col items-center text-xs text-muted-foreground"
        >
          <span>Scroll to learn more</span>
          <motion.div animate={{ y: [0, 6, 0] }} transition={{ duration: 1.5, repeat: Infinity }} className="mt-2 h-6 w-4 rounded-full border border-muted-foreground/30 p-0.5">
            <div className="h-1.5 w-full rounded-full bg-muted-foreground/40" />
          </motion.div>
        </motion.div>
      </section>

      {/* Features */}
      <section className="relative px-4 py-24">
        <div className="container mx-auto max-w-5xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12 text-center"
          >
            <h2 className="mb-3 text-2xl font-bold sm:text-3xl">How It Works</h2>
            <p className="text-muted-foreground">Four agents, one verdict. Each specializes in a different detection method.</p>
          </motion.div>

          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {agents.map((agent, i) => (
              <AgentCard
                key={agent.id}
                agent={agent}
                index={i}
                isOpen={openAgent === agent.id}
                onToggle={() => setOpenAgent(openAgent === agent.id ? null : agent.id)}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="relative border-t border-border px-4 py-24">
        <div className="container mx-auto grid max-w-4xl gap-8 sm:grid-cols-3">
          {[
            { icon: Shield, label: "Accuracy Rate", value: "96.4%" },
            { icon: Zap, label: "Avg Response Time", value: "<2s" },
            { icon: Brain, label: "Agents Working", value: "4" },
          ].map((stat, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.15 }}
              className="flex flex-col items-center gap-2 text-center"
            >
              <stat.icon size={20} className="text-primary" />
              <span className="text-3xl font-black">{stat.value}</span>
              <span className="text-sm text-muted-foreground">{stat.label}</span>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="relative border-t border-border px-4 py-24 text-center">
        <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}>
          <h2 className="mb-4 text-2xl font-bold">Ready to verify your text?</h2>
          <Link
            to="/checker"
            className="inline-flex items-center gap-2 rounded-lg bg-primary px-8 py-3.5 text-sm font-bold text-primary-foreground cyber-glow hover:cyber-glow-strong"
          >
            Launch Checker <ArrowRight size={16} />
          </Link>
        </motion.div>
      </section>
    </motion.div>
  );
};

export default LandingPage;
